// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Board struct {
	ID                   string     `json:"id"`
	Type                 string     `json:"type"`
	User                 *User      `json:"user,omitempty"`
	Description          string     `json:"description"`
	DepartureLatitude    float64    `json:"departure_latitude"`
	DepartureLongitude   float64    `json:"departure_longitude"`
	DestinationLatitude  float64    `json:"destination_latitude"`
	DestinationLongitude float64    `json:"destination_longitude"`
	Reward               string     `json:"reward"`
	StartTime            string     `json:"start_time"`
	CreatedAt            *string    `json:"created_at,omitempty"`
	UpdatedAt            *string    `json:"updated_at,omitempty"`
	Comments             []*Comment `json:"comments"`
}

type BoardInput struct {
	Type                 string  `json:"type"`
	UserID               string  `json:"user_id"`
	Description          string  `json:"description"`
	DepartureLatitude    float64 `json:"departure_latitude"`
	DepartureLongitude   float64 `json:"departure_longitude"`
	DestinationLatitude  float64 `json:"destination_latitude"`
	DestinationLongitude float64 `json:"destination_longitude"`
	Reward               string  `json:"reward"`
	StartTime            string  `json:"start_time"`
	CreatedAt            *string `json:"created_at,omitempty"`
	UpdatedAt            *string `json:"updated_at,omitempty"`
}

type Comment struct {
	ID        string `json:"id"`
	Post      *Board `json:"post"`
	Commenter *User  `json:"commenter"`
	Content   string `json:"content"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type CommentInput struct {
	PostID      string  `json:"post_id"`
	CommenterID string  `json:"commenter_id"`
	Content     string  `json:"content"`
	CreatedAt   *string `json:"created_at,omitempty"`
	UpdatedAt   *string `json:"updated_at,omitempty"`
}

type User struct {
	ID              string     `json:"id"`
	Email           string     `json:"email"`
	Name            string     `json:"name"`
	Password        *string    `json:"password,omitempty"`
	IsDriver        bool       `json:"is_driver"`
	ProfileImageURL *string    `json:"profileImageURL,omitempty"`
	CreatedAt       string     `json:"created_at"`
	UpdatedAt       string     `json:"updated_at"`
	Boards          []*Board   `json:"boards,omitempty"`
	Comments        []*Comment `json:"comments,omitempty"`
}

type UserInput struct {
	Email    string `json:"email"`
	Name     string `json:"name"`
	Password string `json:"password"`
	IsDriver bool   `json:"is_driver"`
}
