services:
  app:
    image: oven/bun:latest
    working_dir: /app
    volumes:
      - type: bind
        source: ./
        target: /app
    user: 1000:1000
    ports:
      - 5173:5173
    tty: true
    stdin_open: true
    command: bun run dev